from abc import ABC, abstractmethod
from typing import Iterable
from jobpilot.models.job import JobPosting, ApplyResult

class BaseProvider(ABC):
    @abstractmethod
    def login(self): ...
    @abstractmethod
    def search(self) -> Iterable[JobPosting]: ...
    @abstractmethod
    def is_easy_apply(self, job: JobPosting) -> bool: ...
    @abstractmethod
    def open_job(self, job: JobPosting): ...
    @abstractmethod
    def apply(self, job: JobPosting) -> ApplyResult: ...
